// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Swipe struct {
	ID        pgtype.UUID
	UserID1   pgtype.UUID
	UserID2   pgtype.UUID
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
	CreatedAt pgtype.Timestamp
}
