services:
  migrate:
    build:
      context: .
    image: ghcr.io/pressly/goose:latest
    container_name: migrate-tool

    secrets:
      - profile_user
      - profile_password
      - profile_db
      - swipes_user
      - swipes_password
      - swipes_db

    environment:
      SWIPES_USER: /run/secrets/swipes_user
      SWIPES_PASSWORD: /run/secrets/swipes_password
      SWIPES_DB: /run/secrets/swipes_db

      PROFILE_USER: /run/secrets/profile_user
      PROFILE_PASSWORD: /run/secrets/profile_password
      PROFILE_DB: /run/secrets/profile_db

    volumes:
      - ./migrate.sh:/migrations/migrate.sh
      - ../../migrations:/migrations
    entrypoint: ["sh", "migrate.sh"]
    depends_on:
      db_swipes:
        condition: service_healthy
      db_profiles:
        condition: service_healthy
    networks:
      - tindart

secrets:
  profile_user:
    file: ../secrets/db_profiles/user
  profile_password:
    file: ../secrets/db_profiles/password
  profile_db:
    file: ../secrets/db_profiles/db
  swipes_user:
    file: ../secrets/db_swipes/user
  swipes_password:
    file: ../secrets/db_swipes/password
  swipes_db:
    file: ../secrets/db_swipes/db
