// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Password    string
	Description string
	Location    postgis.Point
	CreatedAt   pgtype.Timestamp
}
