// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id, username, name, surname, email, password, description, location)
VALUES($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateProfileParams struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Password    string
	Description string
	Location    postgis.Point
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Password,
		arg.Description,
		arg.Location,
	)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec

DELETE FROM profiles WHERE id = $1
`

// , location;
func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT
    id, username, name, surname, email, description,
    ST_X(location::GEOGRAPHY) AS longitude,
    ST_Y(location::GEOGRAPHY) AS latitude
FROM profiles WHERE id = $1
`

type GetProfileRow struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Description string
	Longitude   interface{}
	Latitude    interface{}
}

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Description,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    username = COALESCE($2, username),
    name = COALESCE($3, name),
    surname = COALESCE($4, surname),
    email = COALESCE($5, email),
    password = COALESCE($6, password),
    description = COALESCE($7, description),
    location = COALESCE(ST_SetSRID(ST_MakePoint($8, $9), 4326)::GEOGRAPHY, location)
WHERE id = $1
RETURNING id, username, name, surname, email, description
`

type UpdateProfileParams struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Password    string
	Description string
	Longitude   interface{}
	Latitude    interface{}
}

type UpdateProfileRow struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Description string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Password,
		arg.Description,
		arg.Longitude,
		arg.Latitude,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Description,
	)
	return i, err
}
