// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, password FROM profiles WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO jwt_tokens (id, refresh_token)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET refresh_token = $2
`

type SaveRefreshTokenParams struct {
	ID           pgtype.UUID
	RefreshToken string
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken, arg.ID, arg.RefreshToken)
	return err
}
