// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JwtToken struct {
	ID           pgtype.UUID
	RefreshToken string
}

type Profile struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Password    string
	Description pgtype.Text
	Latitude    pgtype.Float8
	Longitude   pgtype.Float8
	CreatedAt   pgtype.Timestamp
}
