services:
  nginx:
    image: nginx:1.29.6-trixie
    container_name: api-gateway
    restart: always

    ports:
      - "80:80"

    networks:
      - tindart

    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf:ro
