services:
  s3:
    image: rustfs/rustfs:latest
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../configs/rustfs.env
    volumes:
      # - ../configs/rustfs.toml:/etc/rustfs/config.toml
      - ../../data/s3:/data
    networks:
      - tindart
    # command: ["server", "--config", "/etc/rustfs/config.toml"]
