services:
  s3:
    image: rustfs/rustfs:latest
    container_name: s3
    ports:
      - "7000:9000"
      - "7001:9001"
    env_file:
      - ../configs/rustfs.env
    volumes:
      - ../../data/s3:/data
    networks:
      - tindart
