// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db_models

import (
	"database/sql/driver"
	"fmt"

	"github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5/pgtype"
)

type ArtStyleEnum string

const (
	ArtStyleEnumRealism        ArtStyleEnum = "realism"
	ArtStyleEnumMinimalism     ArtStyleEnum = "minimalism"
	ArtStyleEnumFuturism       ArtStyleEnum = "futurism"
	ArtStyleEnumAnarchism      ArtStyleEnum = "anarchism"
	ArtStyleEnumCubism         ArtStyleEnum = "cubism"
	ArtStyleEnumSurrealism     ArtStyleEnum = "surrealism"
	ArtStyleEnumImpressionism  ArtStyleEnum = "impressionism"
	ArtStyleEnumExpressionism  ArtStyleEnum = "expressionism"
	ArtStyleEnumConstructivism ArtStyleEnum = "constructivism"
	ArtStyleEnumDadaism        ArtStyleEnum = "dadaism"
	ArtStyleEnumPhotorealism   ArtStyleEnum = "photorealism"
	ArtStyleEnumRomanticism    ArtStyleEnum = "romanticism"
	ArtStyleEnumCyberpunk      ArtStyleEnum = "cyberpunk"
)

func (e *ArtStyleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtStyleEnum(s)
	case string:
		*e = ArtStyleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtStyleEnum: %T", src)
	}
	return nil
}

type NullArtStyleEnum struct {
	ArtStyleEnum ArtStyleEnum
	Valid        bool // Valid is true if ArtStyleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtStyleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ArtStyleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtStyleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtStyleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtStyleEnum), nil
}

type FavArtStyle struct {
	ID        pgtype.UUID
	ProfileID pgtype.UUID
	Style     ArtStyleEnum
	CreatedAt pgtype.Timestamp
}

type JwtToken struct {
	ID           pgtype.UUID
	RefreshToken pgtype.Text
}

type Photo struct {
	ID        pgtype.UUID
	ProfileID pgtype.UUID
	Url       pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Preference struct {
	ProfileID         pgtype.UUID
	MaxDistanceMeters int32
}

type Profile struct {
	ID          pgtype.UUID
	Username    pgtype.Text
	Name        pgtype.Text
	Surname     pgtype.Text
	Email       pgtype.Text
	Password    pgtype.Text
	Description pgtype.Text
	Location    postgis.Point
	CreatedAt   pgtype.Timestamp
}

type Swipe struct {
	ID        pgtype.UUID
	UserID1   pgtype.UUID
	UserID2   pgtype.UUID
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
	CreatedAt pgtype.Timestamp
}
