// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile.sql

package db_models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFavArtStyle = `-- name: CreateFavArtStyle :exec
INSERT INTO fav_art_styles (id, profile_id, style)
SELECT
    UNNEST($1::uuid[]),
    $2,
    UNNEST($3::text[])::art_style_enum
`

type CreateFavArtStyleParams struct {
	Ids       []pgtype.UUID
	ProfileID pgtype.UUID
	Styles    []pgtype.Text
}

func (q *Queries) CreateFavArtStyle(ctx context.Context, arg CreateFavArtStyleParams) error {
	_, err := q.db.Exec(ctx, createFavArtStyle, arg.Ids, arg.ProfileID, arg.Styles)
	return err
}

const createPhotos = `-- name: CreatePhotos :exec
INSERT INTO photos (id, profile_id, url)
SELECT
    UNNEST($1::uuid[]),
    $2,
    UNNEST($3::text[])
`

type CreatePhotosParams struct {
	Ids       []pgtype.UUID
	ProfileID pgtype.UUID
	Urls      []pgtype.Text
}

func (q *Queries) CreatePhotos(ctx context.Context, arg CreatePhotosParams) error {
	_, err := q.db.Exec(ctx, createPhotos, arg.Ids, arg.ProfileID, arg.Urls)
	return err
}

const createPreferences = `-- name: CreatePreferences :exec
INSERT INTO preferences (profile_id, max_distance_meters)
VALUES ($1, $2)
`

type CreatePreferencesParams struct {
	ProfileID         pgtype.UUID
	MaxDistanceMeters int32
}

func (q *Queries) CreatePreferences(ctx context.Context, arg CreatePreferencesParams) error {
	_, err := q.db.Exec(ctx, createPreferences, arg.ProfileID, arg.MaxDistanceMeters)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id, username, name, surname, email, password, description, location)
VALUES($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_MakePoint($8, $9), 4326))
`

type CreateProfileParams struct {
	ID            pgtype.UUID
	Username      pgtype.Text
	Name          pgtype.Text
	Surname       pgtype.Text
	Email         pgtype.Text
	Password      pgtype.Text
	Description   pgtype.Text
	StMakepoint   interface{}
	StMakepoint_2 interface{}
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Password,
		arg.Description,
		arg.StMakepoint,
		arg.StMakepoint_2,
	)
	return err
}

const deletePhotos = `-- name: DeletePhotos :exec
DELETE FROM photos
WHERE profile_id = $1 AND id = ANY($2::uuid[])
`

type DeletePhotosParams struct {
	ProfileID pgtype.UUID
	Column2   []pgtype.UUID
}

func (q *Queries) DeletePhotos(ctx context.Context, arg DeletePhotosParams) error {
	_, err := q.db.Exec(ctx, deletePhotos, arg.ProfileID, arg.Column2)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT
    p.id, p.username, p.name, p.surname, p.email, p.description,
    ST_X(p.location::GEOMETRY) AS longitude,
    ST_Y(p.location::GEOMETRY) AS latitude,
    COALESCE(ph.photos, '[]') AS photos,
    COALESCE(fav.fav_art_styles, '[]') AS fav_art_styles
FROM profiles p
LEFT JOIN
(
    SELECT profile_id, json_agg(jsonb_build_object('id', id, 'url', url)) AS photos
    FROM photos
    GROUP BY profile_id
)
ph ON ph.profile_id = p.id
LEFT JOIN
(
    SELECT profile_id, json_agg(style) AS fav_art_styles
    FROM fav_art_styles
    GROUP BY profile_id
)
fav ON fav.profile_id = p.id
WHERE p.id = $1
`

type GetProfileRow struct {
	ID           pgtype.UUID
	Username     pgtype.Text
	Name         pgtype.Text
	Surname      pgtype.Text
	Email        pgtype.Text
	Description  pgtype.Text
	Longitude    interface{}
	Latitude     interface{}
	Photos       []byte
	FavArtStyles []byte
}

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Description,
		&i.Longitude,
		&i.Latitude,
		&i.Photos,
		&i.FavArtStyles,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE preferences
SET max_distance_meters = COALESCE($2, max_distance_meters)
WHERE profile_id = $1 RETURNING profile_id, max_distance_meters
`

type UpdatePreferencesParams struct {
	ProfileID         pgtype.UUID
	MaxDistanceMeters pgtype.Int4
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, updatePreferences, arg.ProfileID, arg.MaxDistanceMeters)
	var i Preference
	err := row.Scan(&i.ProfileID, &i.MaxDistanceMeters)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    username = COALESCE($2, username),
    name = COALESCE($3, name),
    surname = COALESCE($4, surname),
    email = COALESCE($5, email),
    password = COALESCE($6, password),
    description = COALESCE($7, description),
    location = COALESCE(ST_SetSRID(ST_MakePoint($8, $9), 4326)::GEOGRAPHY, location)
WHERE id = $1
RETURNING id, username, name, surname, email, description
`

type UpdateProfileParams struct {
	ID          pgtype.UUID
	Username    pgtype.Text
	Name        pgtype.Text
	Surname     pgtype.Text
	Email       pgtype.Text
	Password    pgtype.Text
	Description pgtype.Text
	Longitude   interface{}
	Latitude    interface{}
}

type UpdateProfileRow struct {
	ID          pgtype.UUID
	Username    pgtype.Text
	Name        pgtype.Text
	Surname     pgtype.Text
	Email       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Password,
		arg.Description,
		arg.Longitude,
		arg.Latitude,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Description,
	)
	return i, err
}
