// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stack.sql

package db_models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMatches = `-- name: FindMatches :many
SELECT DISTINCT f2.profile_id
FROM fav_art_styles f1
JOIN fav_art_styles f2 ON f1.style_id = f2.style_id
JOIN profiles p2 ON p2.id = f2.profile_id
JOIN profiles p1 ON p1.id = $1
JOIN preferences pref ON pref.profile_id = $1
WHERE f1.profile_id = $1 AND f2.profile_id != $1 AND ST_DWithin(p1.location, p2.location, pref.max_distance)
`

func (q *Queries) FindMatches(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findMatches, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var profile_id pgtype.UUID
		if err := rows.Scan(&profile_id); err != nil {
			return nil, err
		}
		items = append(items, profile_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProfiles = `-- name: GetAllProfiles :many
SELECT id FROM profiles
`

func (q *Queries) GetAllProfiles(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAllProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
