// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: swipe.sql

package db_models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUpdateSwipe = `-- name: InsertUpdateSwipe :one
INSERT INTO swipes (id, user_id_1, user_id_2, desicion_1, desicion_2)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id_1, user_id_2) DO UPDATE
SET
    desicion_1 = COALESCE($4, swipes.desicion_1),
    desicion_2 = COALESCE($5, swipes.desicion_2)
RETURNING desicion_1, desicion_2
`

type InsertUpdateSwipeParams struct {
	ID        pgtype.UUID
	UserID1   pgtype.UUID
	UserID2   pgtype.UUID
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
}

type InsertUpdateSwipeRow struct {
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
}

func (q *Queries) InsertUpdateSwipe(ctx context.Context, arg InsertUpdateSwipeParams) (InsertUpdateSwipeRow, error) {
	row := q.db.QueryRow(ctx, insertUpdateSwipe,
		arg.ID,
		arg.UserID1,
		arg.UserID2,
		arg.Desicion1,
		arg.Desicion2,
	)
	var i InsertUpdateSwipeRow
	err := row.Scan(&i.Desicion1, &i.Desicion2)
	return i, err
}
