// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: swipe.sql

package db_models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSwipe = `-- name: InsertSwipe :one
INSERT INTO swipes (id, user_id_1, user_id_2, desicion_1, desicion_2)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id_1, user_id_2) DO NOTHING
RETURNING id
`

type InsertSwipeParams struct {
	ID        pgtype.UUID
	UserID1   pgtype.UUID
	UserID2   pgtype.UUID
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
}

func (q *Queries) InsertSwipe(ctx context.Context, arg InsertSwipeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSwipe,
		arg.ID,
		arg.UserID1,
		arg.UserID2,
		arg.Desicion1,
		arg.Desicion2,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateSwipe = `-- name: UpdateSwipe :one
UPDATE swipes
SET desicion_2 = $3
WHERE user_id_1 = $1 AND user_id_2 = $2
RETURNING desicion_1, desicion_2
`

type UpdateSwipeParams struct {
	UserID1   pgtype.UUID
	UserID2   pgtype.UUID
	Desicion2 pgtype.Bool
}

type UpdateSwipeRow struct {
	Desicion1 pgtype.Bool
	Desicion2 pgtype.Bool
}

func (q *Queries) UpdateSwipe(ctx context.Context, arg UpdateSwipeParams) (UpdateSwipeRow, error) {
	row := q.db.QueryRow(ctx, updateSwipe, arg.UserID1, arg.UserID2, arg.Desicion2)
	var i UpdateSwipeRow
	err := row.Scan(&i.Desicion1, &i.Desicion2)
	return i, err
}
