// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Preference struct {
	ProfileID         pgtype.UUID
	MinAge            int32
	MaxAge            int32
	MaxDistanceMeters int32
}

type Profile struct {
	ID          pgtype.UUID
	Username    string
	Name        string
	Surname     string
	Email       string
	Password    string
	Description pgtype.Text
	Location    interface{}
	CreatedAt   pgtype.Timestamp
}
