// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stack.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMatches = `-- name: FindMatches :many
SELECT p.id FROM profiles p
JOIN profiles me ON me.id = $1
JOIN preferences pref ON pref.profile_id = $1
WHERE p.id != $1
AND p.age BETWEEN pref.min_age AND pref.max_age
AND ST_DWithin(me.location, p.location, pref.max_distance_meters)
`

func (q *Queries) FindMatches(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findMatches, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProfiles = `-- name: GetAllProfiles :many
SELECT id FROM profiles
`

func (q *Queries) GetAllProfiles(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAllProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
