FROM golang:1.26.1-alpine AS builder

RUN apk update && apk add --no-cache cronie && touch /var/log/cron.log

COPY cron/stack-cron /etc/crontabs/root

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o stack ./cmd/stack

FROM alpine:3.23.3
COPY --from=builder /app/stack /bin/stack

CMD ["crond", "-f", "-l", "2"]