# Network
bind 0.0.0.0
port 6379
protected-mode yes

# Memory
maxmemory 512mb
maxmemory-policy allkeys-lru

# TTL
hz 10
active-expire-effort 5

# Cache mode
save ""
appendonly no

# Performance
tcp-backlog 511
timeout 0
tcp-keepalive 300

# Logs
loglevel notice
logfile ""

# Data
dir /data
